package com.revature.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-08T11:20:46.122-07:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ws.revature.com/", name = "GuildService")
@XmlSeeAlso({ObjectFactory.class})
public interface GuildService {

    @WebMethod
    @RequestWrapper(localName = "createNewGuild", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.CreateNewGuild")
    @ResponseWrapper(localName = "createNewGuildResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.CreateNewGuildResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.revature.ws.Guild createNewGuild(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getGuildByName", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetGuildByName")
    @ResponseWrapper(localName = "getGuildByNameResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetGuildByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.revature.ws.Guild getGuildByName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
