
package com.revature.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-08T11:20:46.033-07:00
 * Generated source version: 3.3.0
 *
 */
public final class GuildService_GuildServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.revature.com/", "guildService");

    private GuildService_GuildServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GuildService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GuildService_Service ss = new GuildService_Service(wsdlURL, SERVICE_NAME);
        GuildService port = ss.getGuildServiceImplPort();

        {
        System.out.println("Invoking createNewGuild...");
        java.lang.String _createNewGuild_arg0 = "";
        com.revature.ws.Guild _createNewGuild__return = port.createNewGuild(_createNewGuild_arg0);
        System.out.println("createNewGuild.result=" + _createNewGuild__return);


        }
        {
        System.out.println("Invoking getGuildByName...");
        java.lang.String _getGuildByName_arg0 = "";
        com.revature.ws.Guild _getGuildByName__return = port.getGuildByName(_getGuildByName_arg0);
        System.out.println("getGuildByName.result=" + _getGuildByName__return);


        }

        System.exit(0);
    }

}
